#! /bin/bash

echo -e "${background1}${front_colour1}HOSTNAME$end_color = ${background2}${front_colour2}$HOSTNAME$end_color"
echo -e "${background1}${front_colour1}TIMEZONE$end_color = ${background2}${front_colour2}$TIMEZONE$end_color"
echo -e "${background1}${front_colour1}USER$end_color = ${background2}${front_colour2}$USER$end_color"
echo -e "${background1}${front_colour1}OS$end_color = ${background2}${front_colour2}$OS$end_color"
echo -e "${background1}${front_colour1}DATE$end_color = ${background2}${front_colour2}$DATE$end_color"
echo -e "${background1}${front_colour1}UPTIME$end_color = ${background2}${front_colour2}$UPTIME$end_color"
echo -e "${background1}${front_colour1}UPTIME_SEC$end_color = ${background2}${front_colour2}$UPTIME_SEC$end_color"
echo -e "${background1}${front_colour1}IP$end_color = ${background2}${front_colour2}$IP$end_color"
echo -e "${background1}${front_colour1}MASK$end_color = ${background2}${front_colour2}$MASK$end_color"
echo -e "${background1}${front_colour1}GATEWAY$end_color = ${background2}${front_colour2}$GATEWAY$end_color"
echo -e "${background1}${front_colour1}RAM_TOTAL$end_color = ${background2}${front_colour2}$RAM_TOTAL$end_color"
echo -e "${background1}${front_colour1}RAM_USED$end_color = ${background2}${front_colour2}$RAM_USED$end_color"
echo -e "${background1}${front_colour1}RAM_FREE$end_color = ${background2}${front_colour2}$RAM_FREE$end_color"
echo -e "${background1}${front_colour1}SPACE_ROOT$end_color = ${background2}${front_colour2}$SPACE_ROOT$end_color"
echo -e "${background1}${front_colour1}SPACE_ROOT_USED$end_color = ${background2}${front_colour2}$SPACE_ROOT_USED$end_color"
echo -e "${background1}${front_colour1}SPACE_ROOT_FREE$end_color = ${background2}${front_colour2}$SPACE_ROOT_FREE$end_color"
echo " "
echo "Column 1 background = $a"
echo "Column 1 font color = $b"
echo "Column 2 background = $c"
echo "Column 2 font color = $d"
